### ISSUE TITLE
alsa support?

### ISSUE THREAD

**Issue by misitiri** [flathub/org.qutebrowser.qutebrowser#126] opened 2021-12-19 21:45 UTC
I can't hear any playback audio from qutebrowser, but running speaker-test and playing a video via ffplay works as expected. I only have alsa on my system, and when I checked manifest.json, I couldn't find alsa listed. Does this build of qutebrowser not have alsa support and if so why not?

**Comment by tinywrkb** [comment] 2021-12-19 22:25
Try the test build from #127 when the buildbot finishes building it.  
I don't think it will be needed, but you can also try running it with full `/dev` access like this:
```
flatpak run --user --device=all org.qutebrowser.qutebrowser//test
```

I'm not sure if this going to solve it, but nothing else comes to mind regarding the app's packaging.

**Comment by tinywrkb** [comment] 2021-12-20 14:46
> When launching qutebrowser with the --user flag I get an error saying that its not installed.

Did you install the [test build](https://github.com/flathub/org.qutebrowser.qutebrowser/pull/127#issuecomment-997476230)?

I'm guessing that this is not going to change anything, as Qt5WebEngine is probably the module that is handling the audio backend.

> I tried installing the version of qutebrowser packaged by alpine, and I was able to get playback working without messing with anything, but I get a status 11 error when trying to open youtube. I think this may be a distribution specific issue.

I've no idea if ALSA output supposed to work with qutebrowser.  
Can you confirm that ALSA output is working using another Flatpak app?  
From the initial publishing PR, [Waveform11](https://flathub.org/apps/details/com.tracktion.Waveform) supposedly working correctly with ALSA.

**Comment by misitiri** [comment] 2021-12-20 15:10
> Did you install the [test build](https://github.com/flathub/org.qutebrowser.qutebrowser/pull/127#issuecomment-997476230)?

  yes
 
 >I've no idea if ALSA output supposed to work with qutebrowser. Can you confirm that ALSA output is working using another Flatpak app? From the initial publishing PR, [Waveform11](https://flathub.org/apps/details/com.tracktion.Waveform) supposedly working correctly with ALSA.

ALSA output works fine with Waveform

**Comment by tinywrkb** [comment] 2021-12-20 16:20
Looking at the [qt5-qtwebengine build log](https://flathub.org/builds/#/builders/39/builds/8584), we have alsa enabled as `use_alsa=true` is being set automatically, so the problem is probably not with the [base app](https://github.com/flathub/io.qt.qtwebengine.BaseApp).

**Comment by misitiri** [comment] 2021-12-20 17:42
I installed and ran the firefox flatpak and had the same issue, so this might be an issue with my personal setup.

**Comment by misitiri** [comment] 2021-12-23 12:28
When trying to play a youtube video from the version of qutebrowser from the main branch with '--device=all' and the '-T' flag I get the following errors:
> ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
> [85:85:1223/121542.583667:ERROR:alsa_util.cc(204)] PcmOpen: default,Connection refused
> ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused
> [85:85:1223/121542.592941:ERROR:alsa_util.cc(204)] PcmOpen: plug: default,Connection refused

**Comment by tinywrkb** [comment] 2021-12-26 15:47
I'm looking at the strace output, and it seems like you can drop a `asoundrc` into `~/.var/app/org.qutebrowser.qutebrowser/config/alsa/`, so maybe try adding the config file with a default PCM device.

**Comment by tinywrkb** [comment] 2021-12-26 15:59
I can confirm that it's working with PipeWire's ALSA device after blocking PulseAudio access with `--nosocket=pulseaudio`. I just copied PipeWire's ALSA default config as `~/.var/app/org.qutebrowser.qutebrowser/config/alsa/asoundrc`, and confirmed with `ncpamixer` that the audio is played using the PipeWire's ALSA device.

```
pcm.!default {
    type pipewire
    playback_node "-1"
    capture_node  "-1"
    hint {
        show on
        description "Default ALSA Output (currently PipeWire Media Server)"
    }
}

ctl.!default {
    type pipewire
}
```

**Comment by tinywrkb** [comment] 2021-12-26 16:07
The alternative to `~/.var/app/org.qutebrowser.qutebrowser/config/alsa/asoundrc` is `~/.asoundrc` and adding `--filesystem=home` override.  
There are also `/etc/` and `/usr/etc/` but these come from the runtime.  
Maybe `ALSA_CONFIG_PATH` environment variable can be used to pick the config from a different location.

**Comment by tinywrkb** [comment] 2021-12-26 16:22
Closing as a proper `asoundrc` should solve the issue.  
@misitiri if this is still a problem, then re-open.

**Closed by tinywrkb** 2021-12-26 16:22 UTC
