### ISSUE TITLE
Youtube video player not working

### ISSUE THREAD

**Issue by ykgmfq** [flathub/org.qutebrowser.qutebrowser#5] opened 2019-07-01 07:17 UTC
The Youtube video player crashes with an unknown error. All videos from https://tekeye.uk/html/html5-video-test-page work though, as well as http://dash-mse-test.appspot.com/dash-player.html.

This is a bug in the web engine shipped with the platform, as https://github.com/KDE/flatpak-kde-applications/blob/master/org.kde.falkon.json is also affected.

I vaguely remember this problem cropping up after the switch away from the bundled ffmpeg for  the web engine.

**Comment by tinywrkb** [comment] 2021-03-17 21:08
Since this issue was opened we bump the runtime and app versions.  
I can't reproduce this, YouTube works fine for me.  
So I'm closing this.  

If your system still being affected by this after updating the app then please re-open.

**Closed by tinywrkb** 2021-03-17 21:08 UTC
