### ISSUE TITLE
Running the flatpak fails when ~/.var/app/org.qutebrowser.qutebrowser/config/qutebrowser is a symlink

### ISSUE THREAD

**Issue by firecat53** [flathub/org.qutebrowser.qutebrowser#124] opened 2021-12-15 17:26 UTC
I use Gnu stow to track dotfiles. The repository version of qutebrowser handles the symlink fine, but the flatpak fails when the config directory is a symlink.

    $ flatpak run --branch=stable --arch=x86_64 --command=qutebrowser org.qutebrowser.qutebrowser
    Traceback (most recent call last):
      File "/app/bin/qutebrowser", line 33, in <module>
        sys.exit(load_entry_point('qutebrowser==2.4.0', 'gui_scripts', 'qutebrowser')())
      File "/app/lib/python3.9/site-packages/qutebrowser-2.4.0-py3.9.egg/qutebrowser/qutebrowser.py", line 245, in main
      File "/app/lib/python3.9/site-packages/qutebrowser-2.4.0-py3.9.egg/qutebrowser/app.py", line 88, in run
      File "/app/lib/python3.9/site-packages/qutebrowser-2.4.0-py3.9.egg/qutebrowser/utils/standarddir.py", line 355, in init
      File "/app/lib/python3.9/site-packages/qutebrowser-2.4.0-py3.9.egg/qutebrowser/utils/standarddir.py", line 342, in _init_dirs
      File "/app/lib/python3.9/site-packages/qutebrowser-2.4.0-py3.9.egg/qutebrowser/utils/standarddir.py", line 90, in _init_config
      File "/app/lib/python3.9/site-packages/qutebrowser-2.4.0-py3.9.egg/qutebrowser/utils/standarddir.py", line 334, in _create
      File "/usr/lib/python3.9/os.py", line 225, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/home/firecat53/.var/app/org.qutebrowser.qutebrowser/config/qutebrowser'

    $ ls -l .var/app/org.qutebrowser.qutebrowser/config/
    total 4
    drwx------. 1 firecat53 firecat53  12 Dec 13 21:33 pulse
    lrwxrwxrwx. 1 firecat53 firecat53 110 Dec 15 09:11 qutebrowser -> 
    ../../../../docs/family/scott/src/dotfiles/qutebrowser/.var/app/org.qutebrowser.qutebrowser/config/qutebrowser
    -r--r--r--. 1 firecat53 firecat53   0 Dec 13 21:32 user-dirs.dirs

It works correctly when that directory is converted to a regular directory. I have no idea why it would fail since the `os.makedirs` call in utils/standarddir.py contains the `exist_ok=True` flag.

Fedora 35.

    $ flatpak info org.qutebrowser.qutebrowser

    qutebrowser - A keyboard-driven web browser

                ID: org.qutebrowser.qutebrowser
              Ref: app/org.qutebrowser.qutebrowser/x86_64/stable
            Arch: x86_64
        Branch: stable
       Version: 2.4.0
       License: GPL-3.0
          Origin: flathub
     Collection: org.flathub.Stable
    Installation: system
        Installed: 253.6 MB
        Runtime: org.kde.Platform/x86_64/5.15-21.08
               Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: b76d70b83c85f663aa78b97588df3fd17b402660f0713a14f7b66b0c6e45a9fe
      Parent: f882e427e56ce486132ca2ead948ca131e750d76c543d0535162db935674009b
     Subject: Add back python-toml as sip depedency after 8f71f85110974c24cc25af7d4b2c1971903eea19 (153b764a)
        Date: 2021-12-05 13:11:48 +0000

**Comment by tinywrkb** [comment] 2021-12-15 18:07
Check that the sandbox can access the symlink target.

```
# enter the sandbox
flatpak run --command=bash org.qutebrowser.qutebrowser
# check if target is there
ls -l /path/to/target
```

If the symlink target is not accessible, then add filesystem permission override with `flatpak override` or Flatseal. See `flatpak-override.1` man page.

Closing as this is not a bug. If you have more general queries about how to use Flatpak and not specific about the packaging of qutebrowser, then you can ask in the [forums](https://discourse.flathub.org) or [Matrix channel](https://matrix.to/#/#flatpak:matrix.org) or [Reddit](https://www.reddit.com/r/flatpak/).

**Closed by tinywrkb** 2021-12-15 18:07 UTC

**Comment by firecat53** [comment] 2021-12-15 18:26
Sorry for the noise and thanks for the education!
